package com.komsomol.rustream.data.search

import android.content.Context
import androidx.datastore.preferences.core.edit
import androidx.datastore.preferences.core.stringPreferencesKey
import com.komsomol.rustream.data.settings.dataStore
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.runBlocking
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Куки YouTube из WebView-логина. Нужны, чтобы yt-dlp не упирался в
 * «Sign in to confirm you're not a bot»: авторизованный запрос ботом не считается.
 * yt-dlp принимает куки только файлом в формате Netscape (--cookies), поэтому
 * из «сырой» строки WebView собираем cookies.txt в приватной папке приложения.
 */
@Singleton
class YoutubeCookieStore @Inject constructor(
    @ApplicationContext private val context: Context
) {
    @Volatile private var cachedCookies: String? = null

    companion object {
        private val KEY_COOKIES = stringPreferencesKey("youtube_webview_cookies")
        private const val COOKIE_FILE = "youtube_cookies.txt"
        // Домены, куки которых нужны для авторизации на YouTube
        private val HOSTS = listOf(".youtube.com", ".google.com")
    }

    fun saveCookies(rawCookies: String) {
        runBlocking { context.dataStore.edit { it[KEY_COOKIES] = rawCookies } }
        cachedCookies = rawCookies
        writeNetscapeFile(rawCookies)
    }

    fun getRawCookies(): String =
        cachedCookies ?: runBlocking {
            context.dataStore.data.map { it[KEY_COOKIES] ?: "" }.first()
        }.also { cachedCookies = it }

    /** Залогинен, если есть куки сессии Google (SID/SAPISID и т.п.) */
    fun isLoggedIn(): Boolean {
        val raw = getRawCookies()
        if (raw.isBlank()) return false
        return raw.contains("SAPISID") || raw.contains("__Secure-3PSID") ||
            raw.contains("LOGIN_INFO")
    }

    fun clearCookies() {
        runBlocking { context.dataStore.edit { it.remove(KEY_COOKIES) } }
        cachedCookies = ""
        runCatching { cookieFile().delete() }
    }

    fun cookieFile(): File = File(context.filesDir, COOKIE_FILE)

    /** Путь к готовому cookies.txt, если куки есть; иначе null */
    fun cookieFilePathOrNull(): String? {
        val f = cookieFile()
        if (!f.exists() && getRawCookies().isNotBlank()) writeNetscapeFile(getRawCookies())
        return if (f.exists() && f.length() > 0) f.absolutePath else null
    }

    /** Собрать cookies.txt в формате Netscape из строки "k=v; k2=v2" WebView */
    private fun writeNetscapeFile(raw: String) {
        try {
            val sb = StringBuilder()
            sb.append("# Netscape HTTP Cookie File\n")
            sb.append("# Generated by RuStream for yt-dlp\n\n")
            val pairs = raw.split(";")
                .mapNotNull { part ->
                    val i = part.indexOf('=')
                    if (i <= 0) null
                    else part.substring(0, i).trim() to part.substring(i + 1).trim()
                }
                .filter { it.first.isNotBlank() }
            // WebView отдаёт куки без домена — дублируем на нужные хосты YouTube
            for (host in HOSTS) {
                for ((name, value) in pairs) {
                    // domain \t includeSubdomains \t path \t secure \t expiry \t name \t value
                    sb.append(host).append("\tTRUE\t/\tTRUE\t")
                        .append(0).append('\t')
                        .append(name).append('\t').append(value).append('\n')
                }
            }
            cookieFile().writeText(sb.toString())
        } catch (_: Exception) {
        }
    }
}
